In [2]:
import numpy as np
import pandas as pd

scores = np.random.randint(50, 101, size=(50, 5))
scores_pd = pd.DataFrame(scores,columns=['國文','英文','數學','地理','歷史'],index=range(1,51))
scores_pd.T

,1,2,3,4,5,6,7,8,9,10,...,41,42,43,44,45,46,47,48,49,50
國文,98,93,62,57,97,59,82,83,70,100,...,65,57,81,75,71,51,98,99,100,60
英文,98,53,98,58,74,80,85,82,63,73,...,80,84,89,72,53,56,72,92,50,85
數學,61,53,52,62,97,96,95,72,96,75,...,78,59,85,57,88,74,72,70,94,62
地理,56,94,51,76,66,99,52,100,96,60,...,57,95,91,99,70,78,83,72,95,87
歷史,82,99,67,59,66,61,74,73,57,93,...,60,94,79,82,70,86,86,59,92,61

In [3]:
scores_pd.index.name = "學號"
scores_pd.columns.name = "科目"
sum_value = scores_pd.sum(axis=1)
mean_value = np.mean(scores_pd,axis=1)

In [4]:
scores_pd['總分'] = sum_value
scores_pd['平均'] = mean_value
scores_pd

科目   國文  英文  數學   地理   歷史   總分    平均
學號
1    98  98  61   56   82  395  79.0
2    93  53  53   94   99  392  78.4
3    62  98  52   51   67  330  66.0
4    57  58  62   76   59  312  62.4
5    97  74  97   66   66  400  80.0
6    59  80  96   99   61  395  79.0
7    82  85  95   52   74  388  77.6
8    83  82  72  100   73  410  82.0
9    70  63  96   96   57  382  76.4
10  100  73  75   60   93  401  80.2
11   81  97  72   99   68  417  83.4
12   91  93  63   79   62  388  77.6
13   71  91  96   60  100  418  83.6
14   95  88  78   68   79  408  81.6
15   76  66  64   51   70  327  65.4
16   77  91  54   76   68  366  73.2
17   72  63  66   80   59  340  68.0
18   74  55  67   53   62  311  62.2
19   79  93  51   68   97  388  77.6
20   83  78  54   81   54  350  70.0
21   51  79  95   86   66  377  75.4
22   83  78  90   60   71  382  76.4
23   51  62  67   67   80  327  65.4
24   94  96  93   59   65  407  81.4
25   97  89  52   77   55  370  74.0
26   63  62  81   61   99  366  73.2
27   58  93  54   69   72  346  69.2
28   60  96  50   64   89  359  71.8
29   92  83  92   52   63  382  76.4
30   78  72  85   84   93  412  82.4
31   58  59  98   68   84  367  73.4
32   64  97  94   56   78  389  77.8
33   87  70  92   94   78  421  84.2
34   72  69  64   88   65  358  71.6
35   72  93  81   71   84  401  80.2
36   58  69  65   50   93  335  67.0
37   55  62  91   71   58  337  67.4
38   71  87  81   53   54  346  69.2
39   52  68  84   62   86  352  70.4
40   99  89  77   86   78  429  85.8
41   65  80  78   57   60  340  68.0
42   57  84  59   95   94  389  77.8
43   81  89  85   91   79  425  85.0
44   75  72  57   99   82  385  77.0
45   71  53  88   70   70  352  70.4
46   51  56  74   78   86  345  69.0
47   98  72  72   83   86  411  82.2
48   99  92  70   72   59  392  78.4
49  100  50  94   95   92  431  86.2
50   60  85  62   87   61  355  71.0

In [5]:
#排序
scores_pd1 = scores_pd.sort_values(by='總分',ascending=False)
scores_pd1

科目   國文  英文  數學   地理   歷史   總分    平均
學號
49  100  50  94   95   92  431  86.2
40   99  89  77   86   78  429  85.8
43   81  89  85   91   79  425  85.0
33   87  70  92   94   78  421  84.2
13   71  91  96   60  100  418  83.6
11   81  97  72   99   68  417  83.4
30   78  72  85   84   93  412  82.4
47   98  72  72   83   86  411  82.2
8    83  82  72  100   73  410  82.0
14   95  88  78   68   79  408  81.6
24   94  96  93   59   65  407  81.4
35   72  93  81   71   84  401  80.2
10  100  73  75   60   93  401  80.2
5    97  74  97   66   66  400  80.0
6    59  80  96   99   61  395  79.0
1    98  98  61   56   82  395  79.0
2    93  53  53   94   99  392  78.4
48   99  92  70   72   59  392  78.4
32   64  97  94   56   78  389  77.8
42   57  84  59   95   94  389  77.8
7    82  85  95   52   74  388  77.6
19   79  93  51   68   97  388  77.6
12   91  93  63   79   62  388  77.6
44   75  72  57   99   82  385  77.0
9    70  63  96   96   57  382  76.4
29   92  83  92   52   63  382  76.4
22   83  78  90   60   71  382  76.4
21   51  79  95   86   66  377  75.4
25   97  89  52   77   55  370  74.0
31   58  59  98   68   84  367  73.4
26   63  62  81   61   99  366  73.2
16   77  91  54   76   68  366  73.2
28   60  96  50   64   89  359  71.8
34   72  69  64   88   65  358  71.6
50   60  85  62   87   61  355  71.0
45   71  53  88   70   70  352  70.4
39   52  68  84   62   86  352  70.4
20   83  78  54   81   54  350  70.0
38   71  87  81   53   54  346  69.2
27   58  93  54   69   72  346  69.2
46   51  56  74   78   86  345  69.0
17   72  63  66   80   59  340  68.0
41   65  80  78   57   60  340  68.0
37   55  62  91   71   58  337  67.4
36   58  69  65   50   93  335  67.0
3    62  98  52   51   67  330  66.0
15   76  66  64   51   70  327  65.4
23   51  62  67   67   80  327  65.4
4    57  58  62   76   59  312  62.4
18   74  55  67   53   62  311  62.2

In [6]:
scores_pd1['排名'] = scores_pd1['總分'].rank(axis=0,method='min',ascending=False)

In [7]:
scores_pd1
scores_pd1.iloc[-5:]

科目  國文  英文  數學  地理  歷史   總分    平均    排名
學號
3   62  98  52  51  67  330  66.0  46.0
15  76  66  64  51  70  327  65.4  47.0
23  51  62  67  67  80  327  65.4  47.0
4   57  58  62  76  59  312  62.4  49.0
18  74  55  67  53  62  311  62.2  50.0

In [8]:
scores_pd1.map(lambda v:float(v))

科目     國文    英文    數學     地理     歷史     總分    平均    排名
學號
49  100.0  50.0  94.0   95.0   92.0  431.0  86.2   1.0
40   99.0  89.0  77.0   86.0   78.0  429.0  85.8   2.0
43   81.0  89.0  85.0   91.0   79.0  425.0  85.0   3.0
33   87.0  70.0  92.0   94.0   78.0  421.0  84.2   4.0
13   71.0  91.0  96.0   60.0  100.0  418.0  83.6   5.0
11   81.0  97.0  72.0   99.0   68.0  417.0  83.4   6.0
30   78.0  72.0  85.0   84.0   93.0  412.0  82.4   7.0
47   98.0  72.0  72.0   83.0   86.0  411.0  82.2   8.0
8    83.0  82.0  72.0  100.0   73.0  410.0  82.0   9.0
14   95.0  88.0  78.0   68.0   79.0  408.0  81.6  10.0
24   94.0  96.0  93.0   59.0   65.0  407.0  81.4  11.0
35   72.0  93.0  81.0   71.0   84.0  401.0  80.2  12.0
10  100.0  73.0  75.0   60.0   93.0  401.0  80.2  12.0
5    97.0  74.0  97.0   66.0   66.0  400.0  80.0  14.0
6    59.0  80.0  96.0   99.0   61.0  395.0  79.0  15.0
1    98.0  98.0  61.0   56.0   82.0  395.0  79.0  15.0
2    93.0  53.0  53.0   94.0   99.0  392.0  78.4  17.0
48   99.0  92.0  70.0   72.0   59.0  392.0  78.4  17.0
32   64.0  97.0  94.0   56.0   78.0  389.0  77.8  19.0
42   57.0  84.0  59.0   95.0   94.0  389.0  77.8  19.0
7    82.0  85.0  95.0   52.0   74.0  388.0  77.6  21.0
19   79.0  93.0  51.0   68.0   97.0  388.0  77.6  21.0
12   91.0  93.0  63.0   79.0   62.0  388.0  77.6  21.0
44   75.0  72.0  57.0   99.0   82.0  385.0  77.0  24.0
9    70.0  63.0  96.0   96.0   57.0  382.0  76.4  25.0
29   92.0  83.0  92.0   52.0   63.0  382.0  76.4  25.0
22   83.0  78.0  90.0   60.0   71.0  382.0  76.4  25.0
21   51.0  79.0  95.0   86.0   66.0  377.0  75.4  28.0
25   97.0  89.0  52.0   77.0   55.0  370.0  74.0  29.0
31   58.0  59.0  98.0   68.0   84.0  367.0  73.4  30.0
26   63.0  62.0  81.0   61.0   99.0  366.0  73.2  31.0
16   77.0  91.0  54.0   76.0   68.0  366.0  73.2  31.0
28   60.0  96.0  50.0   64.0   89.0  359.0  71.8  33.0
34   72.0  69.0  64.0   88.0   65.0  358.0  71.6  34.0
50   60.0  85.0  62.0   87.0   61.0  355.0  71.0  35.0
45   71.0  53.0  88.0   70.0   70.0  352.0  70.4  36.0
39   52.0  68.0  84.0   62.0   86.0  352.0  70.4  36.0
20   83.0  78.0  54.0   81.0   54.0  350.0  70.0  38.0
38   71.0  87.0  81.0   53.0   54.0  346.0  69.2  39.0
27   58.0  93.0  54.0   69.0   72.0  346.0  69.2  39.0
46   51.0  56.0  74.0   78.0   86.0  345.0  69.0  41.0
17   72.0  63.0  66.0   80.0   59.0  340.0  68.0  42.0
41   65.0  80.0  78.0   57.0   60.0  340.0  68.0  42.0
37   55.0  62.0  91.0   71.0   58.0  337.0  67.4  44.0
36   58.0  69.0  65.0   50.0   93.0  335.0  67.0  45.0
3    62.0  98.0  52.0   51.0   67.0  330.0  66.0  46.0
15   76.0  66.0  64.0   51.0   70.0  327.0  65.4  47.0
23   51.0  62.0  67.0   67.0   80.0  327.0  65.4  47.0
4    57.0  58.0  62.0   76.0   59.0  312.0  62.4  49.0
18   74.0  55.0  67.0   53.0   62.0  311.0  62.2  50.0

In [9]:
def calulate(s):
    #return 自訂的series
    custom_series = pd.Series([s.min(),s.max(),s.median(),s.std()],index=["最低分數","最高分數","中間值","標準差"])
    return custom_series
scores_pd1.iloc[:,:5].apply(calulate)

科目            國文         英文         數學          地理          歷史
最低分數   51.000000  50.000000  50.000000   50.000000   54.000000
最高分數  100.000000  98.000000  98.000000  100.000000  100.000000
中間值    74.500000  79.500000  74.500000   71.000000   72.500000
標準差    15.680691  14.266058  15.484673   15.581255   13.660609

In [10]:
def calulate1(s):
    #return 自訂的series
    s_bool = s < 60
    return s_bool.sum()

scores_pd1["不及格的課目"] = scores_pd1.iloc[:,:5].apply(calulate1,axis=1)

In [11]:
scores_pd1

科目   國文  英文  數學   地理   歷史   總分    平均    排名  不及格的課目
學號
49  100  50  94   95   92  431  86.2   1.0       1
40   99  89  77   86   78  429  85.8   2.0       0
43   81  89  85   91   79  425  85.0   3.0       0
33   87  70  92   94   78  421  84.2   4.0       0
13   71  91  96   60  100  418  83.6   5.0       0
11   81  97  72   99   68  417  83.4   6.0       0
30   78  72  85   84   93  412  82.4   7.0       0
47   98  72  72   83   86  411  82.2   8.0       0
8    83  82  72  100   73  410  82.0   9.0       0
14   95  88  78   68   79  408  81.6  10.0       0
24   94  96  93   59   65  407  81.4  11.0       1
35   72  93  81   71   84  401  80.2  12.0       0
10  100  73  75   60   93  401  80.2  12.0       0
5    97  74  97   66   66  400  80.0  14.0       0
6    59  80  96   99   61  395  79.0  15.0       1
1    98  98  61   56   82  395  79.0  15.0       1
2    93  53  53   94   99  392  78.4  17.0       2
48   99  92  70   72   59  392  78.4  17.0       1
32   64  97  94   56   78  389  77.8  19.0       1
42   57  84  59   95   94  389  77.8  19.0       2
7    82  85  95   52   74  388  77.6  21.0       1
19   79  93  51   68   97  388  77.6  21.0       1
12   91  93  63   79   62  388  77.6  21.0       0
44   75  72  57   99   82  385  77.0  24.0       1
9    70  63  96   96   57  382  76.4  25.0       1
29   92  83  92   52   63  382  76.4  25.0       1
22   83  78  90   60   71  382  76.4  25.0       0
21   51  79  95   86   66  377  75.4  28.0       1
25   97  89  52   77   55  370  74.0  29.0       2
31   58  59  98   68   84  367  73.4  30.0       2
26   63  62  81   61   99  366  73.2  31.0       0
16   77  91  54   76   68  366  73.2  31.0       1
28   60  96  50   64   89  359  71.8  33.0       1
34   72  69  64   88   65  358  71.6  34.0       0
50   60  85  62   87   61  355  71.0  35.0       0
45   71  53  88   70   70  352  70.4  36.0       1
39   52  68  84   62   86  352  70.4  36.0       1
20   83  78  54   81   54  350  70.0  38.0       2
38   71  87  81   53   54  346  69.2  39.0       2
27   58  93  54   69   72  346  69.2  39.0       2
46   51  56  74   78   86  345  69.0  41.0       2
17   72  63  66   80   59  340  68.0  42.0       1
41   65  80  78   57   60  340  68.0  42.0       1
37   55  62  91   71   58  337  67.4  44.0       2
36   58  69  65   50   93  335  67.0  45.0       2
3    62  98  52   51   67  330  66.0  46.0       2
15   76  66  64   51   70  327  65.4  47.0       1
23   51  62  67   67   80  327  65.4  47.0       1
4    57  58  62   76   59  312  62.4  49.0       3
18   74  55  67   53   62  311  62.2  50.0       2